"""create roles table

Revision ID: 16320f5646e9
Revises: 
Create Date: 2026-08-22 21:54:11.243869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16320f5646e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_vehicle_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_bin_code'), table_name='waste_bins')
    op.drop_index(op.f('idx_bin_location'), table_name='waste_bins')
    op.drop_table('waste_bins')
    op.add_column(
    'roles',
    sa.Column('name', sa.String(length=50), nullable=True)
        )
    op.drop_constraint(op.f('roles_role_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'description')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'role_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_role_name_key'), 'roles', ['role_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'name')
    op.create_table('waste_bins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bin_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_fill_level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'MAINTENANCE'::character varying]::text[])", name=op.f('waste_bins_status_check')),
    sa.CheckConstraint('capacity > 0', name=op.f('waste_bins_capacity_check')),
    sa.CheckConstraint('current_fill_level >= 0 AND current_fill_level <= 100', name=op.f('waste_bins_current_fill_level_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('waste_bins_pkey')),
    sa.UniqueConstraint('bin_code', name=op.f('waste_bins_bin_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_bin_location'), 'waste_bins', ['location_name'], unique=False)
    op.create_index(op.f('idx_bin_code'), 'waste_bins', ['bin_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=20), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name=op.f('users_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_users_role'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('driver_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'AVAILABLE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['AVAILABLE'::character varying, 'ON_ROUTE'::character varying, 'MAINTENANCE'::character varying]::text[])", name=op.f('vehicles_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey')),
    sa.UniqueConstraint('vehicle_number', name=op.f('vehicles_vehicle_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_vehicle_number'), 'vehicles', ['vehicle_number'], unique=False)
    # ### end Alembic commands ###
