"""add ai classification fields

Revision ID: a1aaa58d901f
Revises: c71304a948ae
Create Date: 2026-08-25 00:27:43.891065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aaa58d901f'
down_revision: Union[str, Sequence[str], None] = 'c71304a948ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_reports', sa.Column('ai_waste_type', sa.String(length=50), nullable=True))
    op.add_column('waste_reports', sa.Column('ai_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_reports', 'ai_confidence')
    op.drop_column('waste_reports', 'ai_waste_type')
    # ### end Alembic commands ###
