"""initial schema

Revision ID: e08a8e7037cf
Revises: 
Create Date: 2026-09-23 15:57:21.302030
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e08a8e7037cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index('ix_audit_org_created', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_table('emission_factors',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('fuel', 'electricity', 'waste_treatment', 'other', name='factorcategory', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('uncertainty_pct', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factors')),
    sa.UniqueConstraint('code', 'version', name='uq_emission_factor_code_version'),
    sa.UniqueConstraint('code', name=op.f('uq_emission_factors_code'))
    )
    op.create_table('jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('media_assets',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('uploader_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('image', 'document', name='mediakind', native_enum=False, length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('scan_status', sa.Enum('pending', 'clean', 'failed', name='scanstatus', native_enum=False, length=16), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_index(op.f('ix_media_assets_checksum_sha256'), 'media_assets', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_media_assets_organization_id'), 'media_assets', ['organization_id'], unique=False)
    op.create_table('organizations',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('org_type', sa.Enum('municipality', 'municipal_corporation', 'private_operator', 'residential_community', 'campus', 'industrial_facility', 'commercial_facility', 'nonprofit', 'other', name='orgtype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='orgstatus'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('allow_citizen_signup', sa.Boolean(), nullable=False),
    sa.Column('allow_anonymous_reports', sa.Boolean(), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_permissions'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_roles'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_inferences',
    sa.Column('task', sa.Enum('waste_classification', 'complaint_classification', 'complaint_summarization', 'anomaly_detection', 'demand_forecast', 'assistant', name='aitask', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'needs_review', name='aistatus', native_enum=False, length=16), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=True),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('input_ref', sa.Uuid(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_ai_inferences_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_inferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_ai_inferences_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_inferences'))
    )
    op.create_index('ix_ai_inferences_org_task', 'ai_inferences', ['organization_id', 'task'], unique=False)
    op.create_index(op.f('ix_ai_inferences_organization_id'), 'ai_inferences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_inferences_status'), 'ai_inferences', ['status'], unique=False)
    op.create_index(op.f('ix_ai_inferences_task'), 'ai_inferences', ['task'], unique=False)
    op.create_table('carbon_records',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('scope', sa.Enum('scope1', 'scope2', 'scope3', 'avoided', name='emissionscope', native_enum=False, length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('activity_value', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('activity_unit', sa.String(length=48), nullable=False),
    sa.Column('factor_code', sa.String(length=96), nullable=True),
    sa.Column('factor_version', sa.String(length=16), nullable=True),
    sa.Column('co2e_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quality', sa.Enum('measured', 'estimated', 'modeled', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_carbon_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_records'))
    )
    op.create_index('ix_carbon_records_org_period', 'carbon_records', ['organization_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_carbon_records_organization_id'), 'carbon_records', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('report_update', 'complaint_update', 'alert', 'route_assignment', 'reward', 'system', name='notificationcategory', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index('ix_notifications_recipient_created', 'notifications', ['recipient_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('operational_units',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_operational_units_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_units')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_unit_code')
    )
    op.create_index(op.f('ix_operational_units_organization_id'), 'operational_units', ['organization_id'], unique=False)
    op.create_table('org_invitations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_code', sa.String(length=48), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_org_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_org_invitations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_org_invitations_token_hash'))
    )
    op.create_index(op.f('ix_org_invitations_organization_id'), 'org_invitations', ['organization_id'], unique=False)
    op.create_table('org_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_code', sa.String(length=48), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_org_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_org_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_org_memberships_organization_id'), 'org_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_org_memberships_user_id'), 'org_memberships', ['user_id'], unique=False)
    op.create_table('org_usage_counters',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('citizen_count', sa.Integer(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_org_usage_counters_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_org_usage_counters'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reward_ledger',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('signup', 'report_submitted', 'report_resolved', 'complaint_resolved', 'recycling_verified', 'achievement', name='rewardreason', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('reference_type', sa.String(length=48), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reward_ledger_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_ledger'))
    )
    op.create_index(op.f('ix_reward_ledger_organization_id'), 'reward_ledger', ['organization_id'], unique=False)
    op.create_index('ix_reward_ledger_user', 'reward_ledger', ['user_id', 'awarded_at'], unique=False)
    op.create_index(op.f('ix_reward_ledger_user_id'), 'reward_ledger', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_code', sa.String(length=48), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], name=op.f('fk_role_permissions_permission_code_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], name=op.f('fk_role_permissions_role_code_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_code', 'permission_code', name=op.f('pk_role_permissions'))
    )
    op.create_table('waste_categories',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=9), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('default_handling_guidance', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_waste_categories_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_categories')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_waste_category_code')
    )
    op.create_index(op.f('ix_waste_categories_organization_id'), 'waste_categories', ['organization_id'], unique=False)
    op.create_table('ai_reviews',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('inference_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('corrected_output', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['inference_id'], ['ai_inferences.id'], name=op.f('fk_ai_reviews_inference_id_ai_inferences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_ai_reviews_reviewer_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_reviews'))
    )
    op.create_index(op.f('ix_ai_reviews_inference_id'), 'ai_reviews', ['inference_id'], unique=False)
    op.create_index(op.f('ix_ai_reviews_organization_id'), 'ai_reviews', ['organization_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('compactor_truck', 'tipper_truck', 'van', 'ev_van', 'tricycle', 'loader', 'other', name='vehicletype', native_enum=False, length=32), nullable=False),
    sa.Column('fuel_type', sa.Enum('diesel', 'petrol', 'cng', 'electric', 'hybrid', name='fueltype', native_enum=False, length=16), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('capacity_volume_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'maintenance', 'retired', name='vehiclestatus', native_enum=False, length=16), nullable=False),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('depot_lat', sa.Float(), nullable=True),
    sa.Column('depot_lng', sa.Float(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('current_route_id', sa.Uuid(), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position_is_simulated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['current_route_id'], ['routes.id'], name=op.f('fk_vehicles_current_route_id_routes'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_vehicles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['operational_units.id'], name=op.f('fk_vehicles_unit_id_operational_units'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_vehicle_code')
    )
    op.create_index(op.f('ix_vehicles_organization_id'), 'vehicles', ['organization_id'], unique=False)
    op.create_table('waste_treatments',
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('waste_category_id', sa.Uuid(), nullable=True),
    sa.Column('destination', sa.String(length=48), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quality', sa.Enum('measured', 'estimated', 'modeled', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_waste_treatments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_category_id'], ['waste_categories.id'], name=op.f('fk_waste_treatments_waste_category_id_waste_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_treatments'))
    )
    op.create_index(op.f('ix_waste_treatments_organization_id'), 'waste_treatments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_waste_treatments_treatment_date'), 'waste_treatments', ['treatment_date'], unique=False)
    op.create_table('zones',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('color_hex', sa.String(length=9), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lng', sa.Float(), nullable=False),
    sa.Column('bbox_min_lat', sa.Float(), nullable=False),
    sa.Column('bbox_min_lng', sa.Float(), nullable=False),
    sa.Column('bbox_max_lat', sa.Float(), nullable=False),
    sa.Column('bbox_max_lng', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_zones_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['operational_units.id'], name=op.f('fk_zones_unit_id_operational_units'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_zone_code')
    )
    op.create_index('ix_zones_org', 'zones', ['organization_id'], unique=False)
    op.create_index(op.f('ix_zones_organization_id'), 'zones', ['organization_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metric', sa.Enum('fill_pct', 'temperature_c', 'battery_pct', 'offline_hours', name='alertrulemetric', native_enum=False, length=32), nullable=False),
    sa.Column('operator', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'high', 'critical', name='alertseverity', native_enum=False, length=16), nullable=False),
    sa.Column('device_kind', sa.Enum('smart_bin', 'fill_sensor', 'environmental_sensor', 'gps_tracker', 'other', name='devicekind', native_enum=False, length=32), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alert_rules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_alert_rules_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_organization_id'), 'alert_rules', ['organization_id'], unique=False)
    op.create_table('collection_points',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('curbside', 'bin_station', 'transfer_station', 'commercial_dropoff', 'household', name='pointkind', native_enum=False, length=32), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=True),
    sa.Column('households_served', sa.Integer(), nullable=True),
    sa.Column('capacity_volume_m3', sa.Float(), nullable=True),
    sa.Column('est_fill_pct', sa.Float(), nullable=True),
    sa.Column('pickup_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_collection_points_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_collection_points_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_points')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_collection_point_code')
    )
    op.create_index(op.f('ix_collection_points_latitude'), 'collection_points', ['latitude'], unique=False)
    op.create_index(op.f('ix_collection_points_longitude'), 'collection_points', ['longitude'], unique=False)
    op.create_index('ix_collection_points_org', 'collection_points', ['organization_id'], unique=False)
    op.create_index(op.f('ix_collection_points_organization_id'), 'collection_points', ['organization_id'], unique=False)
    op.create_table('driver_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_vehicle_id'], ['vehicles.id'], name=op.f('fk_driver_profiles_default_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_driver_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_driver_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_driver_profiles_user_id'))
    )
    op.create_index(op.f('ix_driver_profiles_organization_id'), 'driver_profiles', ['organization_id'], unique=False)
    op.create_table('routes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'in_progress', 'completed', 'cancelled', name='routestatus', native_enum=False, length=16), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_user_id', sa.Uuid(), nullable=True),
    sa.Column('depot_lat', sa.Float(), nullable=False),
    sa.Column('depot_lng', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_duration_min', sa.Float(), nullable=True),
    sa.Column('planned_weight_kg', sa.Float(), nullable=True),
    sa.Column('stops_count', sa.Integer(), nullable=False),
    sa.Column('optimization', sa.JSON(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('geometry_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_routes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name=op.f('fk_routes_driver_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_routes_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_routes_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_routes_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_route_code')
    )
    op.create_index(op.f('ix_routes_organization_id'), 'routes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_routes_service_date'), 'routes', ['service_date'], unique=False)
    op.create_table('waste_reports',
    sa.Column('reporter_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('anon_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=320), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_media_id', sa.Uuid(), nullable=True),
    sa.Column('category_guess', sa.String(length=48), nullable=True),
    sa.Column('confirmed_category_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_accuracy_m', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=320), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'triaged', 'in_progress', 'resolved', 'rejected', 'closed', name='reportstatus', native_enum=False, length=24), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'urgent', name='reportseverity', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('citizen_app', 'web', 'field', 'hotline', name='reportsource', native_enum=False, length=16), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('ai_inference_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ai_inference_id'], ['ai_inferences.id'], name=op.f('fk_waste_reports_ai_inference_id_ai_inferences'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_waste_reports_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['confirmed_category_id'], ['waste_categories.id'], name=op.f('fk_waste_reports_confirmed_category_id_waste_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_waste_reports_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_media_id'], ['media_assets.id'], name=op.f('fk_waste_reports_photo_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], name=op.f('fk_waste_reports_reporter_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_waste_reports_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_reports'))
    )
    op.create_index(op.f('ix_waste_reports_anon_fingerprint'), 'waste_reports', ['anon_fingerprint'], unique=False)
    op.create_index(op.f('ix_waste_reports_latitude'), 'waste_reports', ['latitude'], unique=False)
    op.create_index(op.f('ix_waste_reports_longitude'), 'waste_reports', ['longitude'], unique=False)
    op.create_index('ix_waste_reports_org_created', 'waste_reports', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_waste_reports_org_status', 'waste_reports', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_waste_reports_organization_id'), 'waste_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_waste_reports_status'), 'waste_reports', ['status'], unique=False)
    op.create_table('collection_events',
    sa.Column('collection_point_id', sa.Uuid(), nullable=False),
    sa.Column('waste_category_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'missed', 'skipped', 'partial', name='eventstatus', native_enum=False, length=16), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('collector_user_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('contamination_flag', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=48), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], name=op.f('fk_collection_events_collection_point_id_collection_points'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collector_user_id'], ['users.id'], name=op.f('fk_collection_events_collector_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_collection_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_collection_events_route_id_routes'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_collection_events_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waste_category_id'], ['waste_categories.id'], name=op.f('fk_collection_events_waste_category_id_waste_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_events')),
    sa.UniqueConstraint('collection_point_id', 'scheduled_date', name='uq_collection_event_point_date')
    )
    op.create_index('ix_collection_events_org_date', 'collection_events', ['organization_id', 'scheduled_date'], unique=False)
    op.create_index('ix_collection_events_org_status', 'collection_events', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_collection_events_organization_id'), 'collection_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_collection_events_scheduled_date'), 'collection_events', ['scheduled_date'], unique=False)
    op.create_table('collection_schedules',
    sa.Column('collection_point_id', sa.Uuid(), nullable=False),
    sa.Column('waste_category_id', sa.Uuid(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'biweekly', 'monthly', name='schedulefrequency', native_enum=False, length=16), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('weeks_interval', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], name=op.f('fk_collection_schedules_collection_point_id_collection_points'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_collection_schedules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_category_id'], ['waste_categories.id'], name=op.f('fk_collection_schedules_waste_category_id_waste_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_schedules'))
    )
    op.create_index(op.f('ix_collection_schedules_collection_point_id'), 'collection_schedules', ['collection_point_id'], unique=False)
    op.create_index(op.f('ix_collection_schedules_organization_id'), 'collection_schedules', ['organization_id'], unique=False)
    op.create_table('complaints',
    sa.Column('waste_report_id', sa.Uuid(), nullable=True),
    sa.Column('reporter_user_id', sa.Uuid(), nullable=True),
    sa.Column('complainant_contact', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('missed_collection', 'bin_damaged', 'overflow', 'odor', 'illegal_dumping', 'staff_conduct', 'billing', 'app_issue', 'other', name='complaintcategory', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'triaged', 'assigned', 'in_progress', 'resolved', 'closed', 'rejected', name='complaintstatus', native_enum=False, length=24), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='complaintpriority', native_enum=False, length=16), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_complaints_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_complaints_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], name=op.f('fk_complaints_reporter_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waste_report_id'], ['waste_reports.id'], name=op.f('fk_complaints_waste_report_id_waste_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_complaints_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index('ix_complaints_org_created', 'complaints', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_complaints_org_status', 'complaints', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_organization_id'), 'complaints', ['organization_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('device_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('smart_bin', 'fill_sensor', 'environmental_sensor', 'gps_tracker', 'other', name='devicekind', native_enum=False, length=32), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=12), nullable=False),
    sa.Column('status', sa.Enum('registered', 'active', 'suspended', 'revoked', name='devicestatus', native_enum=False, length=16), nullable=False),
    sa.Column('collection_point_id', sa.Uuid(), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('firmware', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('current_fill_pct', sa.Float(), nullable=True),
    sa.Column('current_temperature_c', sa.Float(), nullable=True),
    sa.Column('current_battery_pct', sa.Float(), nullable=True),
    sa.Column('last_telemetry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], name=op.f('fk_devices_collection_point_id_collection_points'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_devices_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_devices_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_device_key'), 'devices', ['device_key'], unique=True)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('collection_point_id', sa.Uuid(), nullable=False),
    sa.Column('planned_arrival_offset_min', sa.Float(), nullable=True),
    sa.Column('est_distance_from_prev_km', sa.Float(), nullable=True),
    sa.Column('est_duration_from_prev_min', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'skipped', 'failed', name='stopstatus', native_enum=False, length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('contamination_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], name=op.f('fk_route_stops_collection_point_id_collection_points'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'sequence_no', name='uq_route_stop_seq')
    )
    op.create_index(op.f('ix_route_stops_organization_id'), 'route_stops', ['organization_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('waste_report_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_waste_report_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['waste_reports.id'], name=op.f('fk_waste_report_events_report_id_waste_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_report_events'))
    )
    op.create_index(op.f('ix_waste_report_events_organization_id'), 'waste_report_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_waste_report_events_report_id'), 'waste_report_events', ['report_id'], unique=False)
    op.create_table('alerts',
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'high', 'critical', name='alertseverity', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='alertstatus', native_enum=False, length=16), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alerts_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alerts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_alerts_route_id_routes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alerts_rule_id_alert_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('rule_id', 'device_id', 'triggered_at', name='uq_alert_dedup')
    )
    op.create_index('ix_alerts_org_status', 'alerts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('complaint_comments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_complaint_comments_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_comments_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_comments'))
    )
    op.create_index(op.f('ix_complaint_comments_complaint_id'), 'complaint_comments', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_comments_organization_id'), 'complaint_comments', ['organization_id'], unique=False)
    op.create_table('telemetry_readings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fill_pct', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('signal_strength_dbm', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('device', 'simulator', 'manual', name='telemetrysource', native_enum=False, length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_telemetry_readings_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_readings'))
    )
    op.create_index('ix_telemetry_device_recorded', 'telemetry_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_telemetry_org_recorded', 'telemetry_readings', ['organization_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_org_recorded', table_name='telemetry_readings')
    op.drop_index('ix_telemetry_device_recorded', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_index(op.f('ix_complaint_comments_organization_id'), table_name='complaint_comments')
    op.drop_index(op.f('ix_complaint_comments_complaint_id'), table_name='complaint_comments')
    op.drop_table('complaint_comments')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_index('ix_alerts_org_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_waste_report_events_report_id'), table_name='waste_report_events')
    op.drop_index(op.f('ix_waste_report_events_organization_id'), table_name='waste_report_events')
    op.drop_table('waste_report_events')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_organization_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_key'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_organization_id'), table_name='complaints')
    op.drop_index('ix_complaints_org_status', table_name='complaints')
    op.drop_index('ix_complaints_org_created', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_collection_schedules_organization_id'), table_name='collection_schedules')
    op.drop_index(op.f('ix_collection_schedules_collection_point_id'), table_name='collection_schedules')
    op.drop_table('collection_schedules')
    op.drop_index(op.f('ix_collection_events_scheduled_date'), table_name='collection_events')
    op.drop_index(op.f('ix_collection_events_organization_id'), table_name='collection_events')
    op.drop_index('ix_collection_events_org_status', table_name='collection_events')
    op.drop_index('ix_collection_events_org_date', table_name='collection_events')
    op.drop_table('collection_events')
    op.drop_index(op.f('ix_waste_reports_status'), table_name='waste_reports')
    op.drop_index(op.f('ix_waste_reports_organization_id'), table_name='waste_reports')
    op.drop_index('ix_waste_reports_org_status', table_name='waste_reports')
    op.drop_index('ix_waste_reports_org_created', table_name='waste_reports')
    op.drop_index(op.f('ix_waste_reports_longitude'), table_name='waste_reports')
    op.drop_index(op.f('ix_waste_reports_latitude'), table_name='waste_reports')
    op.drop_index(op.f('ix_waste_reports_anon_fingerprint'), table_name='waste_reports')
    op.drop_table('waste_reports')
    op.drop_index(op.f('ix_routes_service_date'), table_name='routes')
    op.drop_index(op.f('ix_routes_organization_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_driver_profiles_organization_id'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_collection_points_organization_id'), table_name='collection_points')
    op.drop_index('ix_collection_points_org', table_name='collection_points')
    op.drop_index(op.f('ix_collection_points_longitude'), table_name='collection_points')
    op.drop_index(op.f('ix_collection_points_latitude'), table_name='collection_points')
    op.drop_table('collection_points')
    op.drop_index(op.f('ix_alert_rules_organization_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_zones_organization_id'), table_name='zones')
    op.drop_index('ix_zones_org', table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_waste_treatments_treatment_date'), table_name='waste_treatments')
    op.drop_index(op.f('ix_waste_treatments_organization_id'), table_name='waste_treatments')
    op.drop_table('waste_treatments')
    op.drop_index(op.f('ix_vehicles_organization_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_ai_reviews_organization_id'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_inference_id'), table_name='ai_reviews')
    op.drop_table('ai_reviews')
    op.drop_index(op.f('ix_waste_categories_organization_id'), table_name='waste_categories')
    op.drop_table('waste_categories')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_reward_ledger_user_id'), table_name='reward_ledger')
    op.drop_index('ix_reward_ledger_user', table_name='reward_ledger')
    op.drop_index(op.f('ix_reward_ledger_organization_id'), table_name='reward_ledger')
    op.drop_table('reward_ledger')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('org_usage_counters')
    op.drop_index(op.f('ix_org_memberships_user_id'), table_name='org_memberships')
    op.drop_index(op.f('ix_org_memberships_organization_id'), table_name='org_memberships')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_org_invitations_organization_id'), table_name='org_invitations')
    op.drop_table('org_invitations')
    op.drop_index(op.f('ix_operational_units_organization_id'), table_name='operational_units')
    op.drop_table('operational_units')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_carbon_records_organization_id'), table_name='carbon_records')
    op.drop_index('ix_carbon_records_org_period', table_name='carbon_records')
    op.drop_table('carbon_records')
    op.drop_index(op.f('ix_ai_inferences_task'), table_name='ai_inferences')
    op.drop_index(op.f('ix_ai_inferences_status'), table_name='ai_inferences')
    op.drop_index(op.f('ix_ai_inferences_organization_id'), table_name='ai_inferences')
    op.drop_index('ix_ai_inferences_org_task', table_name='ai_inferences')
    op.drop_table('ai_inferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_media_assets_organization_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_checksum_sha256'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('emission_factors')
    op.drop_index('ix_audit_org_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
