/* EcoMind-AI design system: reusable presentational components. */

import { type ReactNode, useEffect } from 'react'
import { clsx } from 'clsx'
import { Loader2, X } from 'lucide-react'
import { statusColor, humanize } from './lib/format'

export function Spinner({ className }: { className?: string }) {
  return <Loader2 className={clsx('animate-spin', className)} size={18} />
}

export function Badge({
  children,
  tone = 'neutral',
  className,
}: {
  children: ReactNode
  tone?: 'neutral' | 'brand' | 'warn' | 'danger' | 'info' | 'purple'
  className?: string
}) {
  const tones: Record<string, string> = {
    neutral: 'text-slate-300 bg-slate-500/10 border-slate-500/25',
    brand: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/25',
    warn: 'text-amber-400 bg-amber-500/10 border-amber-500/25',
    danger: 'text-rose-400 bg-rose-500/10 border-rose-500/25',
    info: 'text-sky-400 bg-sky-500/10 border-sky-500/25',
    purple: 'text-violet-300 bg-violet-500/10 border-violet-500/25',
  }
  return <span className={clsx('chip border', tones[tone], className)}>{children}</span>
}

export function StatusBadge({ status }: { status: string }) {
  return <span className={clsx('chip border', statusColor(status))}>{humanize(status)}</span>
}

export function DemoBadge() {
  return (
    <span className="chip border border-amber-500/40 bg-amber-500/10 text-amber-300" title="This organization contains clearly-labelled synthetic demo data">
      DEMO DATA
    </span>
  )
}

export function SimBadge({ label = 'SIMULATED' }: { label?: string }) {
  return (
    <span className="chip border border-violet-500/40 bg-violet-500/10 text-violet-300" title="Generated by the labelled simulator — not real hardware telemetry">
      {label}
    </span>
  )
}

export function Panel({
  children,
  className,
  hover,
}: {
  children: ReactNode
  className?: string
  hover?: boolean
}) {
  return <div className={clsx('panel', hover && 'panel-hover', className)}>{children}</div>
}

export function PanelHeader({
  title,
  subtitle,
  actions,
  icon,
}: {
  title: ReactNode
  subtitle?: ReactNode
  actions?: ReactNode
  icon?: ReactNode
}) {
  return (
    <div className="flex items-start justify-between gap-3 border-b border-[var(--color-line)] px-5 py-4">
      <div className="flex items-center gap-3">
        {icon && <div className="text-emerald-400">{icon}</div>}
        <div>
          <h3 className="text-sm font-semibold tracking-tight text-[var(--color-ink)]">{title}</h3>
          {subtitle && <p className="mt-0.5 text-xs text-[var(--color-mute)]">{subtitle}</p>}
        </div>
      </div>
      {actions && <div className="flex items-center gap-2">{actions}</div>}
    </div>
  )
}

export function StatCard({
  label,
  value,
  sub,
  icon,
  tone = 'brand',
}: {
  label: string
  value: ReactNode
  sub?: ReactNode
  icon?: ReactNode
  tone?: 'brand' | 'info' | 'warn' | 'danger' | 'purple'
}) {
  const tones: Record<string, string> = {
    brand: 'text-emerald-400 bg-emerald-500/10',
    info: 'text-sky-400 bg-sky-500/10',
    warn: 'text-amber-400 bg-amber-500/10',
    danger: 'text-rose-400 bg-rose-500/10',
    purple: 'text-violet-300 bg-violet-500/10',
  }
  return (
    <div className="panel panel-hover p-4">
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-semibold uppercase tracking-wider text-[var(--color-faint)]">{label}</span>
        {icon && <div className={clsx('rounded-lg p-1.5', tones[tone])}>{icon}</div>}
      </div>
      <div className="mt-2 text-2xl font-bold tracking-tight text-[var(--color-ink)]">{value}</div>
      {sub && <div className="mt-1 text-xs text-[var(--color-mute)]">{sub}</div>}
    </div>
  )
}

export function EmptyState({ icon, title, hint }: { icon?: ReactNode; title: string; hint?: string }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 px-6 py-14 text-center">
      {icon && <div className="text-[var(--color-faint)]">{icon}</div>}
      <p className="text-sm font-medium text-[var(--color-mute)]">{title}</p>
      {hint && <p className="max-w-sm text-xs text-[var(--color-faint)]">{hint}</p>}
    </div>
  )
}

export function Modal({
  open,
  onClose,
  title,
  children,
  wide,
}: {
  open: boolean
  onClose: () => void
  title: ReactNode
  children: ReactNode
  wide?: boolean
}) {
  useEffect(() => {
    if (!open) return
    const handler = (e: KeyboardEvent) => e.key === 'Escape' && onClose()
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [open, onClose])

  if (!open) return null
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
      onMouseDown={(e) => e.target === e.currentTarget && onClose()}
      role="dialog"
      aria-modal="true"
    >
      <div className={clsx('panel fade-up max-h-[88vh] w-full overflow-auto', wide ? 'max-w-3xl' : 'max-w-lg')}>
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-[var(--color-line)] bg-[var(--color-panel)] px-5 py-4">
          <h3 className="text-sm font-semibold">{title}</h3>
          <button onClick={onClose} className="btn btn-ghost btn-sm" aria-label="Close">
            <X size={16} />
          </button>
        </div>
        <div className="p-5">{children}</div>
      </div>
    </div>
  )
}

export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) {
  return (
    <div>
      <label className="label">{label}</label>
      {children}
      {hint && <p className="mt-1 text-[11px] text-[var(--color-faint)]">{hint}</p>}
    </div>
  )
}

export function Toast({ message, tone = 'brand' }: { message: string; tone?: 'brand' | 'danger' }) {
  return (
    <div
      className={clsx(
        'fixed bottom-6 left-1/2 z-[80] -translate-x-1/2 rounded-xl border px-4 py-2.5 text-sm font-medium shadow-xl backdrop-blur',
        tone === 'brand'
          ? 'border-emerald-500/30 bg-emerald-950/90 text-emerald-200'
          : 'border-rose-500/30 bg-rose-950/90 text-rose-200',
      )}
      role="status"
    >
      {message}
    </div>
  )
}

export function ProgressBar({ value, tone = 'brand' }: { value: number; tone?: 'brand' | 'warn' | 'danger' }) {
  const colors: Record<string, string> = {
    brand: 'bg-emerald-500',
    warn: 'bg-amber-500',
    danger: 'bg-rose-500',
  }
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-[var(--color-line)]">
      <div
        className={clsx('h-full rounded-full transition-all duration-500', colors[tone])}
        style={{ width: `${Math.min(100, Math.max(0, value))}%` }}
      />
    </div>
  )
}

export function KeyValue({ items }: { items: [string, ReactNode][] }) {
  return (
    <dl className="grid grid-cols-1 gap-x-6 gap-y-3 sm:grid-cols-2">
      {items.map(([k, v]) => (
        <div key={k}>
          <dt className="text-[11px] font-semibold uppercase tracking-wider text-[var(--color-faint)]">{k}</dt>
          <dd className="mt-0.5 text-sm text-[var(--color-ink)]">{v}</dd>
        </div>
      ))}
    </dl>
  )
}

export function Tabs({
  tabs,
  active,
  onChange,
}: {
  tabs: { key: string; label: string; count?: number }[]
  active: string
  onChange: (key: string) => void
}) {
  return (
    <div className="flex flex-wrap gap-1 rounded-xl border border-[var(--color-line)] bg-[var(--color-base)] p-1">
      {tabs.map((t) => (
        <button
          key={t.key}
          onClick={() => onChange(t.key)}
          className={clsx(
            'rounded-lg px-3 py-1.5 text-xs font-semibold transition-all',
            active === t.key
              ? 'bg-emerald-500/15 text-emerald-300'
              : 'text-[var(--color-mute)] hover:text-[var(--color-ink)]',
          )}
        >
          {t.label}
          {t.count !== undefined && <span className="ml-1.5 text-[10px] opacity-60">{t.count}</span>}
        </button>
      ))}
    </div>
  )
}

export function ErrorNote({ message }: { message: string | null }) {
  if (!message) return null
  return (
    <div className="rounded-lg border border-rose-500/30 bg-rose-500/10 px-3 py-2 text-xs text-rose-300" role="alert">
      {message}
    </div>
  )
}
